### ISSUE TITLE
How should I understand the different set for depth(3) and pose(5) in --seq_length?

### ISSUE THREAD

**Issue by SlingHe** [yzcjtr/GeoNet#10]
In the tutorial, you mention that 
## Note that for replicating depth and pose results, the --seq_length is suggested to be 3 and 5 respectively.
However in your source code, depth and pose estimation are trained together. How can you set different seq_length for the whole pipeline? I'm confused for a while.

**Comment by kristijanbartol** [comment]
I guess the best depth results are obtained using --seq_length=3 and separately, the best pose results are obtained using --seq_length=5. I don't think you can have both in the same pipeline.

**Comment by yzcjtr** [comment]
@kristijanbartol is right. They are trained with different sequence lengths as well as splits. You could read the experimentation part of our paper for more details.
