### ISSUE TITLE
figure 5 in paper

### ISSUE THREAD

**Issue by tongpinmo** [yzcjtr/GeoNet#11]
hello ,in Figure 5 of your paper,GeoNet shows clear advantages in occluded ,texture ambiguous regions,and even in shaded dim area.
but  i can't see the comparison of GeoNet Predictions and other methods like DirFlowNetsS,can you show it in the figure ,and where is the difference between GeoNet Error and DirFlowNetsS Error? i can't see the advantages of GeoNet.can you show the accurate data and show more pictures (not just chose the best 4 input)

**Comment by yzcjtr** [comment]
In Fig.5, the 4th & 5th columns show the qualitative comparison between GeoNet and DirFlowNetS. The red or orange regions indicate erroneous predictions.
Regarding accurate quantitative comparison, refer to Table.2 where we clearly show the end point error statistics.

**Comment by tongpinmo** [comment]
oh,oh ,sorry ,i  don' t make clear before ,thank you for your explanation.it means the bigger red and orange regions ,the more erroneous predictions are ?

**Comment by yzcjtr** [comment]
Yes. Such visualization approach follows the official KITTI benchmark, as provided in their [development kit](https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_scene_flow.zip).
