### ISSUE TITLE
single view depth prediciton

### ISSUE THREAD

**Issue by tongpinmo** [yzcjtr/GeoNet#13]
hello ,I have some doubts. 
Have you tried to use more than one images as input to predict depth or what's the advantages and significance of singe-view depth prediction? From some discussion, there is no true depth for a single image.
one more,I think that single view depth has more problems generalizing to previously unseen types of images. For example ,a model trained on outdoor driving sequences is unlikely to work well on indoor scenes ?
what do you think of them ?

**Comment by yzcjtr** [comment]
I haven't tried using two or more images as input to DepthNet. Of course you can try it. Promisingly you will have better generalization ability, but there is no guarantee.
PS, I don't know what you exactly mean by 'there is no true depth for a single image'.
