### ISSUE TITLE
How to find accumulated position error?

### ISSUE THREAD

**Issue by noNameForMe1994** [yzcjtr/GeoNet#18]
Hey,

Great work! However, I have encountered an problem of how to find the accumulated error of predicted positions. The ATE used in the program seems only considers the relatively error in each snippets. I want to find out the accumulated deviation in position between ground truth position and the predicted position from first images in the dataset. How can I achieve this? 

Thank you for your time and patience.

**Comment by yzcjtr** [comment]
You can try to concat these snippets into a complete trajectory. Assuming you have the absolute pose of frame1 as P1 (4*4 transformation matrix), and the relative pose from frame1 to frame2 as P_rel, then you have the absolute pose of frame2 as P1*P_rel.
