### ISSUE TITLE
OutOfRangeError

### ISSUE THREAD

**Issue by dtborders** [yzcjtr/GeoNet#20]
Hi All,
I am trying to use this code for depth estimation in biomedical imaging. I seem to have run into a strange error.
I am running this code on a google cloud instance of a p100 gpu with CUDA 9.0 and python 3.5 installed.
The model starts training, then after a couple thousand iterations, it throws this error. I processed my biomedical imaging data the same way the KITTI data was processed.

Thanks!
Daniel Borders

Unfortunately I didn't save the terminal output from the GeoNet error, but when I tried to run with SfM learner it threw the same error. I have attached that terminal output below. If it would help, I can re-run GeoNet and post the output. 
[terminalOutput .txt](https://github.com/yzcjtr/GeoNet/files/2292649/terminalOutput.txt)

**Comment by yzcjtr** [comment]
Seems like the data loader has problem. Perhaps you can check your training image list and make sure the images exist in the right place. Otherwise I guess it's due to different python or tensorflow versions.
