### ISSUE TITLE
Joint training depth and flow

### ISSUE THREAD

**Issue by SeokjuLee** [yzcjtr/GeoNet#24]
Hi, thanks for sharing codes!
I have a question for joint learning depth and flow networks.
Are there some positive effects when training the tasks all together?

I wonder why you didn't train them all at the last phase.

**Comment by yzcjtr** [comment]
Hi @SeokjuLee , actually I experimented with finetuning all the networks together but found no improvement. This is explained in the **Training Details** in the experimental part of our paper:

> Though the sub-networks can be trained together in an end-to-end fashion, there is no guarantee that the local gradient optimization could get the network to that optimal point. Therefore, we adopt a stage-wise training strategy

**Comment by SeokjuLee** [comment]
@yzcjtr Thanks for the reply. So the ResFlowNet doesn't affect the performance of depth estimation. Is this right? Table 1 shows GeoNet performs significantly better than SfM-Learner [56]. Do SSIM loss and network structure (vgg, resnet) make this huge performance gap?

**Comment by yzcjtr** [comment]
Yes. Both loss and architecture account for the improvement. You can see detailed analysis in Sec 4.2 of our paper.

**Comment by SeokjuLee** [comment]
@yzcjtr Thank you!
