### ISSUE TITLE
rotation error is large?

### ISSUE THREAD

**Issue by Lzc6996** [yzcjtr/GeoNet#30]
Hi, i am trying to reproduce your results with the pretrained model you provided. And I find that, the posenet has very good translation error but large error in rotation. Is there something wrong?

**Comment by yzcjtr** [comment]
Hi @Lzc6996 , can you provide the translation error, rotation error and **ATE** error of your reproduced result on KITTI? Though I think translation error & rotation error are two different things and not directly comparable, ATE error or plotted trajectory may be better to discover the problem.

**Comment by Lzc6996** [comment]
@yzcjtr , thanks for your reply. I get ATE error about 0.012 in kitti seq.09 , just same as your report in GeoNet. But when I plot the trajectory, I find the trajectory is very bad. And then I replace the output rotation with gt rotation, I get a perfect trajectory.  Did you plot the trajectory output by GeoNet? I just want to know if i did something wrong.

**Comment by yzcjtr** [comment]
Good observation. Did you perform scale matching between predictions and groundtruth when plotting the trajectory? If you perform such operation within each snippet of length 5, I believe you could get reasonable visualization. Can you post the plotted trajectory here?

**Comment by Lzc6996** [comment]
Yes, I did the scale matching. 
![00](https://user-images.githubusercontent.com/20632628/48880370-1e1d6180-ee4b-11e8-9d25-d0c3903623da.png)

**Comment by yzcjtr** [comment]
Nice, seems like the result is reasonable though not perfect. The main issue is accumulating error for VO algorithms. From the figure you can see the accumulated rotation error obviously. While I think you cannot tell accumulated translation error here for you have performed scale matching.

**Comment by Lzc6996** [comment]
In the slam problem, for example orb slam, usually it behaves better in rotation error rather than translation. Why can your posenet  get a good result of translation without  good rotation?

**Comment by Lzc6996** [comment]
And we are preparing a paper which wants to quote results of geonet . Do you think the results is fair? or should we do something to get a better results in rotation?

**Comment by zacr0** [comment]
> Yes, I did the scale matching.
> ![00](https://user-images.githubusercontent.com/20632628/48880370-1e1d6180-ee4b-11e8-9d25-d0c3903623da.png)

Excuse me, can you share how did you plot both the predicted and GT trajectories? I've been trying to do it but my results are pretty inacurate.

**Comment by BernardoTeixeira** [comment]
Can any of you please share the code of how to plot the full trajectory from the inference output?

**Comment by DaddyWesker** [comment]
Same question as Bernardo's.

**Comment by Lzc6996** [comment]
@DaddyWesker @BernardoTeixeira 
KITTI's [odometry development kit](http://www.cvlibs.net/datasets/kitti/eval_odometry.php) can help u to do this work.
