### ISSUE TITLE
How can I generate a video with depth view processed by your code

### ISSUE THREAD

**Issue by petitchamp** [yzcjtr/GeoNet#33]
Hello, I would like to generate a video like the one shared in your google drive. 
https://drive.google.com/drive/folders/1Avh8ApcV1mjBTZTo_sNWPIWMl8DedSF2

Does any of your code allows me to do so? dump processed image sequence?

**Comment by yzcjtr** [comment]
Yes, you can use cv2.videowriter for doing this.
