### ISSUE TITLE
A problem of flownet

### ISSUE THREAD

**Issue by seattlegirl** [yzcjtr/GeoNet#36]
Hi, @yzcjtr , great work!
I have some questions.
How do I get the average displacement of pixels between two frames in an optical flow network? How can i testing optical network validate on own data set? Does the data set have to be formatted before testing?
thank you very much!

**Comment by yzcjtr** [comment]
1. You can calculate the magnitude of each displacement vector and average them across the image domain;
2. Yes. You should format your data or rewrite a customized data loader.
