### ISSUE TITLE
How do you evaluate pose?

### ISSUE THREAD

**Issue by danielroth88** [yzcjtr/GeoNet#39]
Hi,
Im running the pose-test mode with the pretrained weights
the output is a txt file per frame with 8 numbers per row (time, x,y,z,qx,qy,qz,qw)
but when I want to evaluate results -  KITTI poses are per sequence and each row is a 3X4 projection matrix
meaning, the kitti_eval can't work

Am I missing something? I followed the instuction in the GitHub (test + evaluate)

**Comment by yzcjtr** [comment]
Hi, did you run the script (kitti_eval/generate_pose_snippets.py) for generating ground truth pose snippets?

**Comment by danielroth88** [comment]
> Hi, did you run the script (kitti_eval/generate_pose_snippets.py) for generating ground truth pose snippets?

I have not! thank you, will try!
