### ISSUE TITLE
What's the dominant factors of having sharp object boundaries?

### ISSUE THREAD

**Issue by dvorak0** [yzcjtr/GeoNet#4]
Great code! Your depth results have much clearer boundaries, compared with that of Tinghui Zhou.

Could you share some insight of persevering edges, especially when the unsupervised loss is used?

**Comment by yzcjtr** [comment]
Hi @dvorak0 ,
I believe the dominant factor lies in image similarity measurement. Direct per-pixel L1 loss easily falls into local minimal, compared with SSIM or other better designed losses. Also, an edge-aware (or 2nd order) smoothness loss can help too.

**Comment by dvorak0** [comment]
Thanks a lot!

**Comment by yzcjtr** [comment]
That's a good point suggested. You can refer to this paper (https://arxiv.org/pdf/1803.03893.pdf) which adopts feature reconstruction loss in addition to image intensity based loss.
