### ISSUE TITLE
About GPU memory

### ISSUE THREAD

**Issue by zmlshiwo** [yzcjtr/GeoNet#42]
Hi,
I have a question. I only have one NVIDIA 1080Ti(11GB) GPU. Is a NVIDIA 1080Ti(11GB) GPU enough to train the whole network(flow+depth+pose)?
Best,
Zhai

**Comment by IddoBotzer** [comment]
Im pretty sure it will do the job

**Comment by yzcjtr** [comment]
Yes, @IddoBotzer is right.
