### ISSUE TITLE
How to visualize depth map?

### ISSUE THREAD

**Issue by zmlshiwo** [yzcjtr/GeoNet#44]
Hi, 
In your paper, I saw the visualization results of depth map. However, when I run the eval_depth.py. I only obtain the error of evaluation and can not obtain the visualization results of depth map. 
On flow task, I run the eval_flow.py. I can obtain the flow color map. So, how to visualize the depth map?
Best,
Mingliang

**Comment by yzcjtr** [comment]
You can refer to this [code](https://github.com/tinghuiz/SfMLearner/blob/2a387b763bc2b6f95b095f929bf751797c9db68a/utils.py#L12-L24). Remember to try another color map for consistency with our paper.
