### ISSUE TITLE
Question about data preparation.

### ISSUE THREAD

**Issue by wangq95** [yzcjtr/GeoNet#45]
Hi, thanks a lot for your promising work, but I am strongly confused about the data preparation for three different tasks, where you said we should to run 'prepare_train_data.py' to get training data with three types -- e.g., kitti_raw_stereo, kitti_raw_eigen and kitti_odom. Using different type, we could get three types training data that are totally different. However, the 'dump_root' is the same, so which type should I choose to train the first stage? Or I just need to choose one of them randomly? Thanks a lot!

**Comment by yzcjtr** [comment]
dump_root is just a placeholder for the target output path. You should set different dump roots according to your needs.

**Comment by xiaomeng9532** [comment]
I also meet some question when I preprocessed the datasets.Can you tell me your wechat.I will be very appreciate if you can help me.
