### ISSUE TITLE
How do you recover full trajectory from 5 pose snippets?

### ISSUE THREAD

**Issue by BernardoTeixeira** [yzcjtr/GeoNet#48]

**Comment by yzcjtr** [comment]
We simply took the 2-frame prediction (from the reference frame to its next frame) within each 5-frame snippet and concat them to form the full trajectory.

**Comment by BernardoTeixeira** [comment]
I am still having trouble recovering the trajectory from the net output pose snippets.
can you please share the code for plotting estimated trajectory ?
thank you in advance
