### ISSUE TITLE
Pretrained pose model of sequence length 3

### ISSUE THREAD

**Issue by bryanyzhu** [yzcjtr/GeoNet#5]
Thanks for the wonderful work. I just tried it out and the results are amazing. I can totally reproduce the results reported in your paper. 

But may you also provide the pre-trained pose model of sequence length 3? Because if I want to resume training of `train_rigid`, I need two pre-trained models both in sequence length 3, otherwise the fully connected layer parameter dimension doesn't match. So if you could also provide that posenet, that would be very helpful. Thank you very much.

**Comment by yzcjtr** [comment]
Hi @bryanyzhu ,
Great to hear your successful reproduction! Sorry that I forgot the need of finetuning existing models. FYI, I have updated the pretrained models in the Google drive.

**Comment by bryanyzhu** [comment]
Thanks a lot, already see the update.
