### ISSUE TITLE
About the training strategy

### ISSUE THREAD

**Issue by zmlshiwo** [yzcjtr/GeoNet#50]
Hi,
I would like to ask about the training strategy of geonet.
1. To reproduce the result of depth, I use the kitti_raw_eigen split to train the depth and pose networks, 30 epoch.
2. To reproduce the result of the residual flow, I first use the kitti_raw_stereo split to train the depth and pose networks, 30 epoch, and then I use the kitti_raw_stereo split to train the residual flow, about 200 epoch.

Is the whole process like this? or
1. Reproduce the result of depth, use kitti_raw_eigen split to train depth and pose networks, 30 epoch
2. To reproduce the result of the residual flow, I first use the kitti_raw_eigen split to train the depth and pose networks, 30 epoch, and then use kitti_raw_stereo split to train the residual flow, about 200 epoch.

I used depth's training strategy to reproduce the results of depth. However, training the residual flow is a bit worse than the paper results. Can you help me to see which one is wrong?

**Comment by yzcjtr** [comment]
You should always use kitti_raw_stereo throughout your stagewise experiment for optical flow.

**Comment by zmlshiwo** [comment]
Ok, that is, to reproduce the result of the residual flow, I first use the kitti_raw_eigen split to train the depth and pose networks, 30 epoch, and then use kitti_raw_stereo split to train the residual flow, about 200 epoch. All right? Using kitti_raw_stereo split on both the first stage and second stage.

**Comment by zmlshiwo** [comment]
Ok, that is, to reproduce the result of the residual flow, I first use the kitti_raw_stereo split to train the depth and pose networks, 30 epoch, and then also use kitti_raw_stereo split to train the residual flow, about 200 epoch. All right? Using kitti_raw_stereo split on both the first stage and second stage.

**Comment by yzcjtr** [comment]
Yes, you should keep the split consistent throughout different stages.
