### ISSUE TITLE
Output problem

### ISSUE THREAD

**Issue by TopGun666** [yzcjtr/GeoNet#56]
Hi @yzcjtr 

Thanks for your work. I have 2 questions about the code.
1. When I run the `eval_pose.py`, I can't get any output of the evaluation.
2.When I run the `test_depth`, I only get the `.npy` file, but it can't be loaded by evaluate code.

Kind regards,

Yu

**Comment by yzcjtr** [comment]
Hi, can you post your log file here for further inspection? Have you configured all the arguments correctly?

**Comment by TopGun666** [comment]
Thanks for your reply. The log file is a little big (about 148 MB).  Could I sent the screenshot to your email? Because the picture can't be updated here. How about the question 1 ? I can't get any pose evaluation result.

**Comment by yzcjtr** [comment]
I meant the error log printed to your screen while running the command. You can also post your script here.

**Comment by TopGun666** [comment]
There is no error log. It runs normally. When I run the first 2 scripts, It ouput is normal. But I can't get any output of the evaluation. Here is my script.

`python geonet_main.py --mode=test_pose --dataset_dir=/home/yhe3/Data/dataset/kitti_odom/ --init_ckpt_file=/home/yhe3/Data/pretrained_models/GeoNet/models/geonet_posenet/model --batch_size=1 --seq_length=5 --pose_test_seq=9 --output_dir=/home/yhe3/Data/project/GeoNet/predictions/poses/09/`

`python kitti_eval/generate_pose_snippets.py --dataset_dir=/home/yhe3/Data/dataset/kitti_odom/ --output_dir=/home/yhe3/Data/project/GeoNet/predictions/poses/snippets/09/ --seq_id=09 --seq_length=5`

`python kitti_eval/eval_pose.py --gtruth_dir=/home/yhe3/Data/project/GeoNet/predictions/poses/snippets/09/ --pred_dir=/home/yhe3/Data/project/GeoNet/predictions/poses/09/`

**Comment by yzcjtr** [comment]
The script looks good to me. Can you confirm the content of the generated pose snippets and predictions? Are they normal? Is your python environment consistent with ours?
In addition, try "python -u" instead of "python".
