### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by baorui123** [yzcjtr/GeoNet#57]
when i try to train the depthnet, the loss cannot go down(due to the rigid_loss part), it is between 1.0-0.2,soon higher and soon lower
i use the data from my own video, so the video should meet what requirement ？
After data preprocess, the concat picture is how like??
help! (i cant get kitti dataset)

**Comment by yzcjtr** [comment]
Hi, the camera recording the video should be moving. To make the warping loss meaningful, you should select an appropriate sampling rate of the video, i.e. try to keep the area of common contents between consecutive frames reasonable.
