### ISSUE TITLE
How to use optical flow model to test my videos?

### ISSUE THREAD

**Issue by eileenlcb** [yzcjtr/GeoNet#58]
In optical flow testing,This task requires calibration data to be able to complete the test. How do I use a model to process my own video clips?
`python kitti_eval/generate_multiview_extension.py --dataset_dir=/path/to/data_scene_flow_multiview/ --calib_dir=/path/to/data_scene_flow_calib/ --dump_root=/path/to/formatted/testdata/ --cam_id=02 --seq_length=3`

**Comment by yzcjtr** [comment]
Hi, I'm not sure what your question is. If you are not enabling the residual flow mode, it's possible to bypass the calibration requirement. If you are asking how to preprocess your own video, you can refer to the script you referenced as an example and customize your own script.
