### ISSUE TITLE
Version of GeoNet

### ISSUE THREAD

**Issue by Chenxi93** [yzcjtr/GeoNet#60]
I would like to ask if there is a new version of GeoNet coming later? Which using python3 or Tensorflow 2.0.  Beacuse i have seen that some tf functions you used is deprecated.  
( in the following months I am gonna use your Network as my Master Thema. )

**Comment by yzcjtr** [comment]
Sorry, I don't have time for this now. You can either use an older version of TF or try to migrate this project to TF 2.0. Any contribution is welcome.

**Comment by essamgoda** [comment]
@Chenxi93 did you try to upgrade GeoNet?
I tried but tf.contrib.slim functionalities and no longer works after upgrading to TensorFlow to 2.0.
@yzcjtr any help?
