### ISSUE TITLE
Upgrading tf.contrib.slim to tf 2.0

### ISSUE THREAD

**Issue by essamgoda** [yzcjtr/GeoNet#65]
I have a problem with my the code which uses tf.contrib.slim functionalities and it does not work with TensorFlow to 2.0.
How can I upgrade?

**Comment by yzcjtr** [comment]
Sorry I haven't used tf for quite a long time. I remember most of the slim ops are related with common modules to build the network architecture (such as conv, avg_pool). Their counterparts should be easy to find in tf2.0, though some detailed discrepancy might exist in the implementation.

**Comment by yzcjtr** [comment]
Also, I find sonnet (https://github.com/deepmind/sonnet) is a good replacement. Hope it helps.
