### ISSUE TITLE
How to get depth ground-truth

### ISSUE THREAD

**Issue by Samyer** [yzcjtr/GeoNet#66]
Hi, I want to ask how to get the depth ground-truth in the paper?

**Comment by yzcjtr** [comment]
Just reproject all the lidar sensor measurements (point cloud) to the image planes.

**Comment by Samyer** [comment]
> Just reproject all the lidar sensor measurements (point cloud) to the image planes.

Thank you for your anwser. Can you share the code about that?

**Comment by yzcjtr** [comment]
It's already available at https://github.com/yzcjtr/GeoNet/blob/5b176025bc63563ef53297aa3d20cc6e575fb833/kitti_eval/depth_evaluation_utils.py#L170-L222.
