### ISSUE TITLE
About FLOPs and parameters

### ISSUE THREAD

**Issue by longmalongma** [yzcjtr/GeoNet#68]
Thanks for your great work! What are the FLOPs and parameters of your segmentation model in the semantic segmentation task on the s3dis dataset? looking forwarding to  your reply.

**Comment by yzcjtr** [comment]
Sorry for the late response. There's no segmentation model or s3dis dataset in this work. If you are referring to calculate the FLOPs/#params for a general tensorflow model, maybe you can check [this blog](https://medium.com/@fanzongshaoxing/model-flops-measurement-in-tensorflow-a84084bbb3b5)?
