### ISSUE TITLE
How to train depth and pose together?

### ISSUE THREAD

**Issue by HilmiK** [yzcjtr/GeoNet#8]
For training, the following command is required to enter:

python geonet_main.py --mode=train_rigid --dataset_dir=/path/to/formatted/data/ --checkpoint_dir=/path/to/save/ckpts/ --learning_rate=0.0002 --seq_length=3 --batch_size=4 --max_steps=350000 

However, there is one parameter for indicating dataset but we have download depth and pose datasets. What should we enter here? 

Also in residual training case, there should be 2 checkpoints as an input. However, it seems that 1 input is required. Can you explain this point, please?

Thanks in advance.

**Comment by yzcjtr** [comment]
1. It depends on your training splits/datasets. You should follow the data preprocessing guide, then specify the _dataset_dir_ as the formatted data;
2. In the first stage (train_rigid mode), your saved model should include both depthnet & posenet. Thus you only need to specify one ckpt.

**Comment by HilmiK** [comment]
1. Does formatted data contain both datasets under directory and main.py understand which one is depth and pose?

**Comment by yzcjtr** [comment]
I'm not sure what you mean. The dataset simply contains image sequences and intrinsic matrices. The depth and pose should be trained in a joint way on the same formatted dataset.

**Comment by HilmiK** [comment]
So, you are saying that I can choose depth or pose(single one is enough) for training at first stage?  Then, train in train flow mode with only flow formatted data?

**Comment by HilmiK** [comment]
Thanks a lot. I could not get the logic from paper, it is very clear now.
